spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update, 운영 환경에서는 validate 혹은 none 권장
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # 세션 설정
  servlet:
    session:
      timeout: 30m  # 세션 타임아웃 설정 (예: 30분)
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: cartoon-for-blind
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}

# 서버 포트 설정
server:
  port: 8080


jwt:
  secret: ${JWT_SECRET}

